# Auto-generated by tune_loss.py
import numpy as np
W = np.array([0.3792465925216675, -0.928326427936554, -0.7354795932769775, 0.7415730953216553, -0.46572983264923096], dtype=np.float32)
B = -0.37071910
THRESH = 0.302021        # frame-level threshold on sigmoid
THRESH_VIDEO = 0.403609  # video-level threshold (EMA+p95)
